"""Shared primitives for the local Kaggle / HF preview-page scripts.

PR 7.2 — both ``scripts/preview_kaggle_page.py`` and
``scripts/preview_hf_page.py`` need to:

* HTML-escape user-controlled strings the same way (and emit the
  same entity form so committed sample HTML doesn't churn between
  scripts);
* construct an ``http.server.ThreadingHTTPServer`` rooted at a
  preview-output directory (chosen for ``allow_reuse_address=True``
  inheritance from ``HTTPServer``);
* start serving + optionally pop a browser tab.

Splitting ``make_server`` away from ``serve`` is what lets the test
suite stand the server up on port 0 in a thread, GET ``/``, and
shut down cleanly — the alternative (calling ``serve_forever``
directly) would require subprocess management and a real port
allocation race.
"""

from __future__ import annotations

import http.server
import json
import sys
import webbrowser
from pathlib import Path
from typing import Any, Final


def escape(value: str) -> str:
    """HTML-escape a single attribute / text value.

    Hand-rolled rather than using ``html.escape`` so the committed
    sample HTML uses the decimal ``&#39;`` entity for ``'`` (matching
    what the preview scripts emitted at PR-open time) — switching to
    ``html.escape``'s ``&#x27;`` would force a regen of every
    committed sample with no observable rendering difference.
    """

    return (
        str(value)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )


def plural(n: int, singular: str, plural_form: str | None = None) -> str:
    """Return ``f"{n} <word>"`` with ``<word>`` pluralised when ``n != 1``.

    Default pluralisation is the trailing-``s`` rule; pass
    ``plural_form`` for irregular cases (none today).  Used by the
    preview-page section-heading counts so output reads as "1 config"
    rather than "1 configs" — the latter was caught in PR review on
    the instructor sample (Copilot finding COPILOT-3).
    """

    word = singular if n == 1 else (plural_form or singular + "s")
    return f"{n} {word}"


#: SPDX-style URL for MIT — schema.org's ``license`` slot wants a URL,
#: not the bare SPDX short-name HF / Kaggle store.  Both previews
#: render the same URL.
LICENSE_URL_MIT: Final[str] = "https://opensource.org/licenses/MIT"

#: Citation template embedded in the JSON-LD ``citation`` slot.  Single-
#: sourced here so the Kaggle and HF previews can't drift on it.  Both
#: previews target the same canonical recipe / seed (the published
#: dataset's identity); change here in lockstep with any recipe rename.
JSONLD_CITATION: Final[str] = (
    "Generated by leadforge (https://github.com/leadforge-dev/leadforge); "
    "recipe b2b_saas_procurement_v1, seed 42."
)

JSONLD_CREATOR: Final[str] = "leadforge"
JSONLD_VERSION: Final[str] = "v1"


def render_jsonld_dataset(
    *,
    name: str,
    description: str,
    license_url: str,
    keywords: list[str],
    citation: str | None = None,
    distribution_paths: list[str] | None = None,
    same_as: list[str] | None = None,
    creator: str | None = None,
    version: str | None = None,
) -> str:
    """Render a schema.org ``Dataset`` JSON-LD ``<script>`` block.

    Goes in the ``<head>`` of the preview HTML so an AI reviewer can
    read structured fields (name, license, keywords, distribution,
    citation) without parsing the markdown body or the bespoke schema
    tables.  The shape mirrors what Kaggle and HuggingFace inject into
    their live dataset pages — keeping the mock previews aligned with
    what the published page will eventually expose.
    """

    payload: dict[str, Any] = {
        "@context": "https://schema.org",
        "@type": "Dataset",
        "name": name,
        "description": description,
        "license": license_url,
        "keywords": sorted(set(keywords)),
        "isAccessibleForFree": True,
    }
    if creator is not None:
        payload["creator"] = {"@type": "Organization", "name": creator}
    if version is not None:
        payload["version"] = version
    if citation is not None:
        payload["citation"] = citation
    if distribution_paths:
        payload["distribution"] = [
            {
                "@type": "DataDownload",
                "encodingFormat": _encoding_format_for(path),
                "contentUrl": path,
            }
            for path in distribution_paths
        ]
    if same_as:
        payload["sameAs"] = list(same_as)
    rendered = json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False)
    # HTML-safe JSON-LD: escape ``<`` / ``>`` / ``&`` to their JSON
    # unicode-escape forms so a hostile string in any value (notably a
    # frontmatter ``pretty_name`` that contains ``<script>``) cannot
    # close the surrounding ``<script type="application/ld+json">``
    # block or get re-interpreted by an HTML parser.  Match the
    # convention used by ``json.dumps(default=...)`` ports of this
    # trick in major frameworks (Rails, Django).
    rendered = rendered.replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")
    return f'<script type="application/ld+json">{rendered}</script>'


def _encoding_format_for(path: str) -> str:
    """Map a filename suffix to a MIME-ish encoding-format token.

    Limited to the suffixes used in the release bundle (parquet, CSV,
    JSON, Markdown, YAML, PNG).  Falls back to ``application/octet-
    stream`` for unknowns — keeps the JSON-LD block well-typed without
    surprising consumers with empty strings.
    """

    suffix = path.rsplit(".", 1)[-1].lower() if "." in path else ""
    return {
        "parquet": "application/vnd.apache.parquet",
        "csv": "text/csv",
        "json": "application/json",
        "md": "text/markdown",
        "yaml": "application/x-yaml",
        "yml": "application/x-yaml",
        "png": "image/png",
    }.get(suffix, "application/octet-stream")


def render_cover(filename: str) -> str:
    """Render a sibling-relative cover-image block.

    Used by both preview scripts; the HF preview previously copied
    the cover into the preview tree without ever rendering it
    (Copilot finding COPILOT-2 — either drop the copy or display
    it; we picked display for symmetry with Kaggle and because HF's
    live page shows the dataset cover too).  Sibling-relative
    ``src`` so the same HTML works for both the runtime preview
    tree (where the image was copied in) and the committed sample
    (which is byte-compared, not served).
    """

    src = escape(filename)
    return f"""<section class="cover">
  <img class="cover__image" src="{src}" alt="Dataset cover image">
</section>"""


def _make_handler_factory(directory: Path) -> type[http.server.SimpleHTTPRequestHandler]:
    """Build a handler subclass that serves from ``directory``.

    ``SimpleHTTPRequestHandler`` accepts a ``directory=`` kwarg in
    Python 3.7+, but threading the path through ``ThreadingHTTPServer``'s
    ``RequestHandlerClass`` requires either a ``functools.partial`` or
    a subclass; subclassing keeps the import surface stdlib-only.
    """

    resolved = str(directory.resolve())

    class _Handler(http.server.SimpleHTTPRequestHandler):
        def __init__(self, *args: Any, **kwargs: Any) -> None:
            super().__init__(*args, directory=resolved, **kwargs)

    return _Handler


def make_server(directory: Path, port: int) -> http.server.ThreadingHTTPServer:
    """Build (don't start) an HTTP server rooted at ``directory``.

    ``ThreadingHTTPServer`` (unlike bare ``socketserver.ThreadingTCPServer``)
    inherits ``allow_reuse_address = True`` from ``HTTPServer`` —
    matters because Ctrl-C → re-run within ~60s would otherwise raise
    ``OSError [Errno 48] Address already in use`` while the socket
    sits in TIME_WAIT.

    Pass ``port=0`` to let the kernel pick a free port; the bound
    port is then on ``server.server_address[1]``.  This is the seam
    that makes ``_serve`` testable (test starts the server in a
    thread, fetches one URL, shuts down).
    """

    return http.server.ThreadingHTTPServer(("", port), _make_handler_factory(directory))


def serve(directory: Path, port: int, *, open_browser: bool) -> None:
    """Start the HTTP server rooted at ``directory`` and block.

    Blocks on ``serve_forever()``; KeyboardInterrupt (Ctrl-C) is the
    documented exit path.  Untested by unit tests because it blocks;
    ``make_server`` is the testable seam.
    """

    httpd = make_server(directory, port)
    bound_port = httpd.server_address[1]
    url = f"http://localhost:{bound_port}/"
    print(f"serving {directory} at {url} — Ctrl-C to stop", file=sys.stderr)
    if open_browser:
        webbrowser.open(url)
    httpd.serve_forever()
