#!/usr/bin/env python3
"""Package the ``leadforge-lead-scoring-v1`` family for Kaggle.

PR 5.1 — first of two PRs in Phase 5 (Platform packaging) of the v1
release roadmap.  This script:

1. Reads each public tier's ``manifest.json`` + ``feature_dictionary.csv``
   + flat CSV header under ``release/`` and assembles a Kaggle
   ``dataset-metadata.json`` that satisfies G11.1 of
   ``docs/release/v1_acceptance_gates.md`` — title length, subtitle
   length, slug length, single licence, ``expectedUpdateFrequency``
   from the approved set, image filename, and
   ``resources[].schema.fields`` listed **in column order** for every
   tabular resource (CSV via the feature dictionary; parquet via the
   Arrow schema).
2. Validates the cover image at ``release/dataset-cover-image.png``
   (≥ 560 × 280 per G11.2; generated by
   ``scripts/generate_cover_image.py``).
3. Writes ``release/kaggle/dataset-metadata.json`` deterministically:
   the same release input produces a byte-identical metadata file
   (audit-artifact-sync pattern; guarded by
   ``tests/scripts/test_package_kaggle_release.py``).
4. Optionally assembles a Kaggle-CLI-shaped upload directory under
   ``release/kaggle/`` as real-file copies of the per-tier bundles
   plus a rewritten copy of ``release/README.md`` whose directory
   diagram and ``../`` links resolve correctly when read on the
   Kaggle dataset page.  An earlier draft used symlinks; we copy
   instead because Kaggle's CLI walks the upload directory with
   ``followlinks=False`` in some versions.

The actual ``kaggle datasets create`` upload lives in PR 7.2; this
script is intentionally publish-free.  ``--dry-run`` validates and
writes the metadata without touching the upload-dir layout, useful
for shape iteration; the default mode also assembles the upload tree.

Failed validation exits with rc=1; pre-flight errors (missing release
dir, missing tier, missing cover image, unsafe ``--kaggle-dir``)
exit with rc=2.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Final

import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
from PIL import Image

# ---------------------------------------------------------------------------
# Kaggle field constraints (chatgpt v2 §19, verified from official docs)
# ---------------------------------------------------------------------------

TITLE_LEN_RANGE: Final[tuple[int, int]] = (6, 50)
SUBTITLE_LEN_RANGE: Final[tuple[int, int]] = (20, 80)
SLUG_LEN_RANGE: Final[tuple[int, int]] = (3, 50)

#: Allowed values for ``expectedUpdateFrequency`` (Kaggle CLI rejects
#: anything else).
APPROVED_UPDATE_FREQUENCIES: Final[tuple[str, ...]] = (
    "never",
    "annually",
    "quarterly",
    "monthly",
    "weekly",
    "daily",
    "hourly",
)

#: Cover-image minimum dimensions per G11.2: 560 × 280 minimum, with
#: 2:1 header / 1:1 thumbnail crops in mind.
COVER_IMAGE_MIN_WIDTH: Final[int] = 560
COVER_IMAGE_MIN_HEIGHT: Final[int] = 280

#: Allowed cover-image extensions per Kaggle docs.
ALLOWED_COVER_IMAGE_SUFFIXES: Final[tuple[str, ...]] = (
    ".png",
    ".jpg",
    ".jpeg",
    ".webp",
)

#: Slug pattern — Kaggle dataset slugs are lowercase alphanumeric with
#: hyphens.  Boundary chars must be alphanumeric so the slug never
#: starts or ends with a hyphen.
SLUG_PATTERN: Final[re.Pattern[str]] = re.compile(r"^[a-z0-9][a-z0-9-]*[a-z0-9]$")

# ---------------------------------------------------------------------------
# Release-specific defaults (G1.2 dataset slug + G11 metadata content)
# ---------------------------------------------------------------------------

DEFAULT_USER_SLUG: Final[str] = "leadforge"
DEFAULT_DATASET_SLUG: Final[str] = "leadforge-lead-scoring-v1"

DEFAULT_TITLE: Final[str] = "LeadForge: Synthetic B2B Lead Scoring (v1)"
DEFAULT_SUBTITLE: Final[str] = "Three-tier synthetic CRM funnel for leakage-aware lead scoring"

DEFAULT_KEYWORDS: Final[tuple[str, ...]] = (
    "b2b",
    "classification",
    "crm",
    "education",
    "lead-scoring",
    "saas",
    "synthetic-data",
    "tabular",
)


@dataclass(frozen=True)
class UserSource:
    """One entry under ``userSpecifiedSources``.

    Defined alongside the constants so ``DEFAULT_USER_SOURCES`` below
    can reference it without a forward declaration; the rest of the
    metadata dataclasses live further down in their own section.
    """

    title: str
    url: str


DEFAULT_USER_SOURCES: Final[tuple[UserSource, ...]] = (
    UserSource(
        title="leadforge source repository",
        url="https://github.com/leadforge-dev/leadforge",
    ),
    UserSource(
        title="v1 release validation report",
        url="https://github.com/leadforge-dev/leadforge/tree/main/release/validation",
    ),
)

DEFAULT_LICENSE_NAME: Final[str] = "MIT"
DEFAULT_UPDATE_FREQUENCY: Final[str] = "never"

DEFAULT_TIERS: Final[tuple[str, ...]] = ("intro", "intermediate", "advanced")
DEFAULT_TASK: Final[str] = "converted_within_90_days"

DEFAULT_RELEASE_DIR: Final[Path] = Path("release")
DEFAULT_KAGGLE_DIR: Final[Path] = Path("release/kaggle")
DEFAULT_COVER_IMAGE: Final[Path] = Path("release/dataset-cover-image.png")

#: Top-level files at ``release/`` that ship to Kaggle alongside the
#: bundles.  README.md is rewritten on the way in (see
#: :func:`_kaggle_readme_text`); LICENSE is taken verbatim.
TOP_LEVEL_DOCS: Final[tuple[str, ...]] = ("README.md", "LICENSE")

#: Tables that may appear in a public bundle, in canonical render
#: order.  ``customers`` and ``subscriptions`` are intentionally
#: absent — their presence in a public bundle would itself be leakage
#: (PR 2.2).
BUNDLE_TABLES: Final[tuple[str, ...]] = (
    "accounts",
    "contacts",
    "leads",
    "touches",
    "sessions",
    "sales_activities",
    "opportunities",
)

#: Mapping from feature_dictionary.csv ``dtype`` (see
#: ``leadforge/schema/dictionaries.py``) to a Frictionless Data
#: Package ``schema.fields[].type`` token, which Kaggle's resource
#: schema uses.
DTYPE_TO_FRICTIONLESS: Final[dict[str, str]] = {
    "string": "string",
    "Int64": "integer",
    "Float64": "number",
    "boolean": "boolean",
}

#: Description for the ``split`` column, which is present in the flat
#: CSV but not in the feature dictionary (it tracks task-split
#: membership rather than describing a feature).
SPLIT_COLUMN_DESCRIPTION: Final[str] = (
    "Task-split membership: one of `train`, `valid`, `test`. "
    "Matches the per-row split assignment in `tasks/converted_within_90_days/`."
)

# ---------------------------------------------------------------------------
# Description / README rewriting
# ---------------------------------------------------------------------------

GITHUB_BLOB_BASE: Final[str] = "https://github.com/leadforge-dev/leadforge/blob/main"

#: The "What's inside" tree diagram in ``release/README.md``.  The
#: published README on Kaggle should describe the *upload* layout
#: (which has dataset-metadata.json + cover image at the top, no
#: instructor companion, no notebooks/validation siblings), not the
#: source-repo layout — we substitute the block on the way out.
KAGGLE_TREE_BLOCK: Final[str] = """```
release/
├── intro/ intermediate/ advanced/    # student_public bundles, one per difficulty tier
│   ├── manifest.json                 # provenance + file hashes
│   ├── dataset_card.md               # auto-rendered per-bundle card
│   ├── feature_dictionary.csv        # authoritative column spec
│   ├── lead_scoring.csv              # flat convenience CSV (all splits)
│   ├── tables/*.parquet              # 7 snapshot-safe relational tables
│   └── tasks/converted_within_90_days/{train,valid,test}.parquet
├── intermediate_instructor/          # research companion: full-horizon tables + metadata/
├── notebooks/01_baseline_lead_scoring.ipynb
└── validation/                       # validation_report.{json,md} + figures
```"""

KAGGLE_UPLOAD_TREE_BLOCK: Final[str] = """```
.
├── intro/ intermediate/ advanced/    # student_public bundles, one per difficulty tier
│   ├── manifest.json                 # provenance + file hashes
│   ├── dataset_card.md               # auto-rendered per-bundle card
│   ├── feature_dictionary.csv        # authoritative column spec
│   ├── lead_scoring.csv              # flat convenience CSV (all splits)
│   ├── tables/*.parquet              # 7 snapshot-safe relational tables
│   └── tasks/converted_within_90_days/{train,valid,test}.parquet
├── dataset-metadata.json             # Kaggle dataset metadata
├── dataset-cover-image.png           # Kaggle cover image
├── README.md                         # Kaggle package README
└── LICENSE
```"""

#: Inline relative link ``](../foo)`` → ``](GITHUB_BLOB_BASE/foo)``
#: for any markdown link that escapes the bundle root.
_PARENT_RELATIVE_LINK: Final[re.Pattern[str]] = re.compile(r"\]\(\.\./([^)]+)\)")

#: The README points at ``validation/validation_report.md`` (a path
#: that lives under ``release/`` but not under the Kaggle upload
#: directory).  Rewrite to a GitHub blob URL so the link works on
#: Kaggle.
_VALIDATION_REPORT_LINK: Final[str] = "](validation/validation_report.md)"
_VALIDATION_REPORT_URL: Final[str] = (
    f"]({GITHUB_BLOB_BASE}/release/validation/validation_report.md)"
)


def _kaggle_readme_text(readme: str) -> str:
    """Apply the Kaggle-specific rewrites to a copy of the release README.

    Rewrites:

    1. Source-repo tree diagram → upload-tree diagram (the published
       README should describe what the *user* sees on Kaggle, not the
       source repo layout).
    2. ``](../foo)`` → ``]({GITHUB_BLOB_BASE}/foo)`` (markdown links
       that escape the bundle root resolve to the source repo on
       GitHub).
    3. ``](validation/validation_report.md)`` → blob URL (the
       validation report does not ship to Kaggle; readers click
       through to GitHub).
    """

    text = readme.replace(KAGGLE_TREE_BLOCK, KAGGLE_UPLOAD_TREE_BLOCK)
    text = _PARENT_RELATIVE_LINK.sub(rf"]({GITHUB_BLOB_BASE}/\1)", text)
    text = text.replace(_VALIDATION_REPORT_LINK, _VALIDATION_REPORT_URL)
    return text


# ---------------------------------------------------------------------------
# Dataclasses — one per top-level metadata block
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class FieldDescriptor:
    """One column entry inside ``resources[].schema.fields``."""

    name: str
    type: str
    description: str | None = None


@dataclass(frozen=True)
class ResourceSchema:
    """Frictionless-style schema declaration for a tabular resource."""

    fields: tuple[FieldDescriptor, ...]


@dataclass(frozen=True)
class Resource:
    """One entry under ``resources``.

    ``schema`` is set to ``None`` for non-tabular resources (markdown,
    JSON manifests).  The renderer drops ``None`` values and
    ``description=None`` field-level entries so the JSON stays clean.
    """

    path: str
    description: str
    schema: ResourceSchema | None = None


@dataclass(frozen=True)
class LicenseSpec:
    """One entry under ``licenses``.  Kaggle requires exactly one."""

    name: str


# ``UserSource`` is defined above (next to ``DEFAULT_USER_SOURCES``) so
# the constant can reference it without forward-declaration tricks.


@dataclass(frozen=True)
class DatasetMetadata:
    """Top-level Kaggle metadata payload.

    These dataclasses are typed records, not invariants — construction
    is unchecked.  Callers MUST run :func:`validate_metadata` before
    relying on the metadata being well-formed; that function is the
    authoritative gate for every Kaggle field constraint.  Doing the
    validation eagerly in ``__post_init__`` would prevent tests from
    constructing deliberately bad payloads to exercise the validator,
    which is why the discipline lives in the validator instead.
    """

    title: str
    id: str
    subtitle: str
    description: str
    isPrivate: bool  # noqa: N815 — Kaggle field name is camelCase
    licenses: tuple[LicenseSpec, ...]
    keywords: tuple[str, ...]
    collaborators: tuple[str, ...]
    expectedUpdateFrequency: str  # noqa: N815 — Kaggle field name
    userSpecifiedSources: tuple[UserSource, ...]  # noqa: N815 — Kaggle field name
    image: str
    resources: tuple[Resource, ...] = field(default_factory=tuple)


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ValidationError:
    """One field-level validation failure."""

    field: str
    message: str


def _validate_length(name: str, value: str, lo: int, hi: int) -> ValidationError | None:
    n = len(value)
    if n < lo or n > hi:
        return ValidationError(
            field=name,
            message=f"length {n} outside Kaggle range [{lo}, {hi}]",
        )
    return None


def _validate_slug(slug: str, *, field_name: str) -> ValidationError | None:
    err = _validate_length(field_name, slug, *SLUG_LEN_RANGE)
    if err is not None:
        return err
    if not SLUG_PATTERN.fullmatch(slug):
        return ValidationError(
            field=field_name,
            message=f"slug {slug!r} must be lowercase alphanumeric with hyphens",
        )
    return None


def _validate_id(value: str) -> list[ValidationError]:
    """Validate the ``user/slug`` id field.

    Kaggle's actual ``dataset-metadata.json`` schema uses
    ``<owner>/<slug>``; the slug-only short form some tooling accepts
    is rejected here so the artefact is upload-ready without
    publish-time fixup.
    """

    errors: list[ValidationError] = []
    if "/" not in value:
        errors.append(ValidationError(field="id", message=f"id {value!r} missing 'user/' prefix"))
        return errors
    user, slug = value.split("/", 1)
    if not user:
        errors.append(ValidationError(field="id", message="user prefix is empty"))
    if not slug:
        errors.append(ValidationError(field="id", message="slug is empty"))
        return errors
    slug_err = _validate_slug(slug, field_name="id (slug)")
    if slug_err is not None:
        errors.append(slug_err)
    return errors


def validate_metadata(metadata: DatasetMetadata) -> list[ValidationError]:
    """Run every Kaggle-side check against a built ``DatasetMetadata``."""

    errors: list[ValidationError] = []

    title_err = _validate_length("title", metadata.title, *TITLE_LEN_RANGE)
    if title_err is not None:
        errors.append(title_err)

    subtitle_err = _validate_length("subtitle", metadata.subtitle, *SUBTITLE_LEN_RANGE)
    if subtitle_err is not None:
        errors.append(subtitle_err)

    errors.extend(_validate_id(metadata.id))

    if len(metadata.licenses) != 1:
        errors.append(
            ValidationError(
                field="licenses",
                message=f"expected exactly one entry, got {len(metadata.licenses)}",
            )
        )

    if metadata.expectedUpdateFrequency not in APPROVED_UPDATE_FREQUENCIES:
        errors.append(
            ValidationError(
                field="expectedUpdateFrequency",
                message=(
                    f"{metadata.expectedUpdateFrequency!r} not in approved values "
                    f"{APPROVED_UPDATE_FREQUENCIES}"
                ),
            )
        )

    image_suffix = Path(metadata.image).suffix.lower()
    if image_suffix not in ALLOWED_COVER_IMAGE_SUFFIXES:
        errors.append(
            ValidationError(
                field="image",
                message=(
                    f"image extension {image_suffix!r} not in allowed Kaggle suffixes "
                    f"{ALLOWED_COVER_IMAGE_SUFFIXES}"
                ),
            )
        )

    if not metadata.resources:
        errors.append(
            ValidationError(field="resources", message="must contain at least one resource")
        )

    for i, res in enumerate(metadata.resources):
        if res.schema is None:
            continue  # non-tabular resource; schema is optional
        if not res.schema.fields:
            errors.append(
                ValidationError(
                    field=f"resources[{i}].schema.fields",
                    message="must contain at least one field when schema is declared",
                )
            )
            continue
        for j, fd in enumerate(res.schema.fields):
            if not fd.name or not fd.type:
                errors.append(
                    ValidationError(
                        field=f"resources[{i}].schema.fields[{j}]",
                        message="each field must declare both name and type",
                    )
                )

    return errors


def validate_cover_image(path: Path) -> list[ValidationError]:
    """Validate that ``path`` exists and meets Kaggle's dimension floor."""

    errors: list[ValidationError] = []
    if not path.exists():
        errors.append(
            ValidationError(
                field="cover_image",
                message=f"cover image not found at {path}",
            )
        )
        return errors
    with Image.open(path) as img:
        width, height = img.size
    if width < COVER_IMAGE_MIN_WIDTH or height < COVER_IMAGE_MIN_HEIGHT:
        errors.append(
            ValidationError(
                field="cover_image",
                message=(
                    f"cover image {width}x{height} below Kaggle minimum "
                    f"{COVER_IMAGE_MIN_WIDTH}x{COVER_IMAGE_MIN_HEIGHT}"
                ),
            )
        )
    return errors


# ---------------------------------------------------------------------------
# Bundle reading + resource building
# ---------------------------------------------------------------------------


def _load_feature_dictionary(path: Path) -> dict[str, FieldDescriptor]:
    """Load ``feature_dictionary.csv`` keyed by column name."""

    df = pd.read_csv(path)
    descriptors: dict[str, FieldDescriptor] = {}
    for _, row in df.iterrows():
        dtype = str(row["dtype"])
        frictionless_type = DTYPE_TO_FRICTIONLESS.get(dtype)
        if frictionless_type is None:
            raise ValueError(
                f"feature_dictionary.csv at {path}: dtype {dtype!r} not mapped to a "
                f"Frictionless Data Package type ({sorted(DTYPE_TO_FRICTIONLESS)!r})"
            )
        name = str(row["name"])
        descriptors[name] = FieldDescriptor(
            name=name,
            type=frictionless_type,
            description=str(row["description"]).strip(),
        )
    return descriptors


def _flat_csv_fields(
    flat_csv_path: Path, feature_dict: dict[str, FieldDescriptor]
) -> tuple[FieldDescriptor, ...]:
    """Build ``schema.fields`` for a flat CSV in CSV column order."""

    columns = list(pd.read_csv(flat_csv_path, nrows=0).columns)
    fields: list[FieldDescriptor] = []
    for col in columns:
        name = str(col)
        if name == "split":
            fields.append(
                FieldDescriptor(name=name, type="string", description=SPLIT_COLUMN_DESCRIPTION)
            )
            continue
        descriptor = feature_dict.get(name)
        if descriptor is None:
            raise ValueError(
                f"flat CSV at {flat_csv_path}: column {name!r} is not present in "
                f"feature_dictionary.csv — feature dictionary is the source of truth"
            )
        fields.append(descriptor)
    return tuple(fields)


def _kaggle_type_from_arrow(dtype: pa.DataType) -> str:
    """Map a pyarrow type to the Frictionless field-type token."""

    if pa.types.is_boolean(dtype):
        return "boolean"
    if pa.types.is_integer(dtype):
        return "integer"
    if pa.types.is_floating(dtype) or pa.types.is_decimal(dtype):
        return "number"
    if pa.types.is_date(dtype) or pa.types.is_timestamp(dtype) or pa.types.is_time(dtype):
        return "datetime"
    return "string"


def fields_from_parquet(path: Path) -> tuple[FieldDescriptor, ...]:
    """Read parquet schema from ``path`` and return ``FieldDescriptor`` rows.

    Kaggle accepts Frictionless schemas on parquet resources too; the
    parquet file's own Arrow metadata is the ground truth for column
    order and types, so we read directly rather than mirroring a CSV
    header.  ``description`` is omitted for parquet fields — relational
    tables don't have per-column docs in the bundle.
    """

    schema = pq.read_schema(path)
    return tuple(FieldDescriptor(name=f.name, type=_kaggle_type_from_arrow(f.type)) for f in schema)


def _load_manifest(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"manifest.json at {path} is not a JSON object")
    return payload


def build_tier_resources(
    release_dir: Path,
    tier: str,
    *,
    task: str = DEFAULT_TASK,
) -> tuple[Resource, ...]:
    """Build the ``Resource`` list for one tier in canonical order.

    Order: flat CSV (with full ``schema.fields``) → feature dictionary
    → task splits (parquet, schema from Arrow) → relational tables
    (parquet, schema from Arrow) → dataset card → manifest.  Kaggle
    renders this list in declared order on the dataset page.
    """

    tier_dir = release_dir / tier
    if not tier_dir.is_dir():
        raise FileNotFoundError(f"tier directory missing: {tier_dir}")

    feature_dict_path = tier_dir / "feature_dictionary.csv"
    feature_dict = _load_feature_dictionary(feature_dict_path)
    flat_csv_path = tier_dir / "lead_scoring.csv"
    fields = _flat_csv_fields(flat_csv_path, feature_dict)

    manifest = _load_manifest(tier_dir / "manifest.json")
    table_inventory = manifest.get("tables", {})
    snapshot_day = manifest.get("snapshot_day")

    resources: list[Resource] = []

    resources.append(
        Resource(
            path=f"{tier}/lead_scoring.csv",
            description=(
                f"{tier.capitalize()} tier flat CSV (all splits concatenated, label retained, "
                f"snapshot_day={snapshot_day}). The `split` column distinguishes "
                f"train/valid/test rows."
            ),
            schema=ResourceSchema(fields=fields),
        )
    )

    resources.append(
        Resource(
            path=f"{tier}/feature_dictionary.csv",
            description=f"{tier.capitalize()} tier feature dictionary (canonical column spec).",
        )
    )

    for split in ("train", "valid", "test"):
        split_path = tier_dir / "tasks" / task / f"{split}.parquet"
        rows = manifest.get("tasks", {}).get(task, {}).get(f"{split}_rows")
        rows_str = f"{rows:,} rows" if isinstance(rows, int) else "row count in manifest"
        resources.append(
            Resource(
                path=f"{tier}/tasks/{task}/{split}.parquet",
                description=(f"{tier.capitalize()} tier {split} split for `{task}` ({rows_str})."),
                schema=ResourceSchema(fields=fields_from_parquet(split_path)),
            )
        )

    for table in BUNDLE_TABLES:
        if table not in table_inventory:
            continue
        table_path = tier_dir / "tables" / f"{table}.parquet"
        row_count = table_inventory[table].get("row_count")
        rows_str = f"{row_count:,} rows" if isinstance(row_count, int) else ""
        suffix = f" ({rows_str})" if rows_str else ""
        resources.append(
            Resource(
                path=f"{tier}/tables/{table}.parquet",
                description=(
                    f"{tier.capitalize()} tier `{table}` relational table{suffix} — snapshot-safe."
                ),
                schema=ResourceSchema(fields=fields_from_parquet(table_path)),
            )
        )

    resources.append(
        Resource(
            path=f"{tier}/dataset_card.md",
            description=f"{tier.capitalize()} tier auto-rendered dataset card.",
        )
    )
    resources.append(
        Resource(
            path=f"{tier}/manifest.json",
            description=(
                f"{tier.capitalize()} tier provenance manifest (recipe, seed, package "
                f"version, file hashes, snapshot_day, redaction contract)."
            ),
        )
    )
    return tuple(resources)


def build_metadata(
    release_dir: Path,
    *,
    tiers: Sequence[str] = DEFAULT_TIERS,
    task: str = DEFAULT_TASK,
    owner: str = DEFAULT_USER_SLUG,
    dataset_slug: str = DEFAULT_DATASET_SLUG,
    title: str = DEFAULT_TITLE,
    subtitle: str = DEFAULT_SUBTITLE,
    description: str | None = None,
    keywords: Sequence[str] = DEFAULT_KEYWORDS,
    license_name: str = DEFAULT_LICENSE_NAME,
    update_frequency: str = DEFAULT_UPDATE_FREQUENCY,
    user_sources: Sequence[UserSource] = DEFAULT_USER_SOURCES,
    cover_image: Path = DEFAULT_COVER_IMAGE,
) -> DatasetMetadata:
    """Assemble a ``DatasetMetadata`` from the release tree.

    When ``description`` is ``None`` (the default) we lift the
    contents of ``release/README.md`` and apply the Kaggle-specific
    rewrites — Kaggle renders the description above the file list, so
    a full dataset card there is more useful than a curated blurb.
    """

    if description is None:
        readme_path = release_dir / "README.md"
        description = _kaggle_readme_text(readme_path.read_text(encoding="utf-8"))

    resources: list[Resource] = []
    for tier in tiers:
        resources.extend(build_tier_resources(release_dir, tier, task=task))

    return DatasetMetadata(
        title=title,
        id=f"{owner}/{dataset_slug}",
        subtitle=subtitle,
        description=description,
        isPrivate=True,
        licenses=(LicenseSpec(name=license_name),),
        keywords=tuple(keywords),
        collaborators=(),
        expectedUpdateFrequency=update_frequency,
        userSpecifiedSources=tuple(user_sources),
        image=cover_image.name,
        resources=tuple(resources),
    )


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _field_to_dict(fd: FieldDescriptor) -> dict[str, Any]:
    payload: dict[str, Any] = {"name": fd.name, "type": fd.type}
    if fd.description is not None:
        payload["description"] = fd.description
    return payload


def _resource_to_dict(resource: Resource) -> dict[str, Any]:
    """Serialise a ``Resource`` to a JSON-primitive dict.

    Drops ``schema`` when ``None``; drops ``description`` from
    individual fields when ``None`` (parquet schemas don't carry
    per-column documentation).
    """

    payload: dict[str, Any] = {
        "path": resource.path,
        "description": resource.description,
    }
    if resource.schema is not None:
        payload["schema"] = {"fields": [_field_to_dict(fd) for fd in resource.schema.fields]}
    return payload


def metadata_to_dict(metadata: DatasetMetadata) -> dict[str, Any]:
    """Convert ``DatasetMetadata`` to a JSON-primitive dict.

    Built field-by-field rather than via ``asdict()`` so resource
    serialisation goes through one path (``_resource_to_dict``) and
    the keywords array is sorted at render time — making the
    determinism contract explicit rather than relying on the
    ``DEFAULT_KEYWORDS`` constant happening to be alphabetised.
    """

    return {
        "title": metadata.title,
        "id": metadata.id,
        "subtitle": metadata.subtitle,
        "description": metadata.description,
        "isPrivate": metadata.isPrivate,
        "licenses": [{"name": lic.name} for lic in metadata.licenses],
        "keywords": sorted(metadata.keywords),
        "collaborators": list(metadata.collaborators),
        "expectedUpdateFrequency": metadata.expectedUpdateFrequency,
        "userSpecifiedSources": [
            {"title": s.title, "url": s.url} for s in metadata.userSpecifiedSources
        ],
        "image": metadata.image,
        "resources": [_resource_to_dict(r) for r in metadata.resources],
    }


def render_metadata_json(metadata: DatasetMetadata) -> str:
    """Render the metadata as a deterministic JSON string.

    ``ensure_ascii=False`` keeps non-ASCII content (em-dashes, the ×
    multiplication sign, smart quotes from the inlined README)
    rendered literally rather than escaped to ``\\u2013`` etc., which
    is essential for ``git diff`` readability when the README evolves.
    """

    return (
        json.dumps(
            metadata_to_dict(metadata),
            indent=2,
            sort_keys=True,
            ensure_ascii=False,
        )
        + "\n"
    )


# ---------------------------------------------------------------------------
# Upload-directory assembly
# ---------------------------------------------------------------------------


def _validate_kaggle_dir_safe(kaggle_dir: Path, release_dir: Path) -> None:
    """Refuse to assemble into a path that aliases something dangerous.

    The packager replaces children of ``kaggle_dir`` (rmtree + recopy)
    so pointing it at ``cwd`` / ``release_dir`` / their parents / the
    filesystem anchor would clobber unrelated content.  This guard
    fires before any disk write.
    """

    resolved = kaggle_dir.resolve()
    blocked = {
        Path(resolved.anchor),
        Path.cwd().resolve(),
        release_dir.resolve(),
        release_dir.resolve().parent,
    }
    if resolved in blocked:
        raise ValueError(f"refusing to assemble into unsafe --kaggle-dir: {kaggle_dir}")


def _replace_file(src: Path, dst: Path) -> None:
    """Copy ``src`` → ``dst``, replacing any existing entry at ``dst``."""

    if dst.is_symlink() or dst.is_file():
        dst.unlink()
    elif dst.exists() and dst.is_dir():
        shutil.rmtree(dst)
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def _replace_dir(src: Path, dst: Path) -> None:
    """Copy directory ``src`` → ``dst``, replacing any existing entry."""

    if dst.is_symlink() or dst.is_file():
        dst.unlink()
    elif dst.exists() and dst.is_dir():
        shutil.rmtree(dst)
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(src, dst)


def assemble_upload_dir(
    release_dir: Path,
    kaggle_dir: Path,
    *,
    tiers: Sequence[str] = DEFAULT_TIERS,
    cover_image: Path = DEFAULT_COVER_IMAGE,
) -> None:
    """Assemble ``kaggle_dir`` for ``kaggle datasets create`` to consume.

    The output tree is a self-contained directory of real files:
    cover image, LICENSE, the rewritten README, and full copies of
    each tier bundle.  Symlinks were considered (and tried in an
    earlier draft) but Kaggle's CLI walks the upload directory with
    ``followlinks=False`` in some versions, silently skipping symlinked
    children — switching to copies removes that fragility at the cost
    of ~15 MB of disk per assembly run, which is gitignored anyway.

    Re-running the assembly is idempotent: ``_replace_file`` and
    ``_replace_dir`` rmtree-then-copy any existing entry.  The README
    is the one file rewritten on the way in (tree diagram + ``../``
    links).  ``--dry-run`` skips this whole function.
    """

    _validate_kaggle_dir_safe(kaggle_dir, release_dir)
    kaggle_dir.mkdir(parents=True, exist_ok=True)

    # Cover image.
    cover_src = release_dir / cover_image.name
    if not cover_src.exists():
        cover_src = cover_image
    _replace_file(cover_src, kaggle_dir / cover_image.name)

    # LICENSE — straight copy, no rewriting.
    license_src = release_dir / "LICENSE"
    if license_src.exists():
        _replace_file(license_src, kaggle_dir / "LICENSE")

    # README.md — real copy with link rewriting so ``../`` links and
    # the directory diagram resolve correctly on the Kaggle dataset
    # page.
    kaggle_readme = kaggle_dir / "README.md"
    if kaggle_readme.is_symlink() or kaggle_readme.is_file():
        kaggle_readme.unlink()
    readme_src = release_dir / "README.md"
    if readme_src.exists():
        kaggle_readme.parent.mkdir(parents=True, exist_ok=True)
        kaggle_readme.write_text(
            _kaggle_readme_text(readme_src.read_text(encoding="utf-8")),
            encoding="utf-8",
        )

    # Per-tier bundles — full directory copies.
    for tier in tiers:
        tier_src = release_dir / tier
        _replace_dir(tier_src, kaggle_dir / tier)


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class PackagerOutcome:
    """Return value from :func:`run_packager` — used by tests + CLI."""

    metadata: DatasetMetadata
    metadata_path: Path
    errors: tuple[ValidationError, ...]
    assembled: bool


def run_packager(
    release_dir: Path,
    *,
    kaggle_dir: Path = DEFAULT_KAGGLE_DIR,
    tiers: Sequence[str] = DEFAULT_TIERS,
    task: str = DEFAULT_TASK,
    owner: str = DEFAULT_USER_SLUG,
    dataset_slug: str = DEFAULT_DATASET_SLUG,
    title: str = DEFAULT_TITLE,
    subtitle: str = DEFAULT_SUBTITLE,
    description: str | None = None,
    keywords: Sequence[str] = DEFAULT_KEYWORDS,
    license_name: str = DEFAULT_LICENSE_NAME,
    update_frequency: str = DEFAULT_UPDATE_FREQUENCY,
    user_sources: Sequence[UserSource] = DEFAULT_USER_SOURCES,
    cover_image: Path = DEFAULT_COVER_IMAGE,
    dry_run: bool = False,
) -> PackagerOutcome:
    """Build, validate, and write the Kaggle metadata.

    With ``dry_run=False`` (the default) the packager additionally
    assembles the Kaggle-CLI-shaped upload directory under
    ``kaggle_dir`` (real-file copies of the per-tier bundles + cover
    image + LICENSE + the rewritten README).  ``dry_run=True`` skips
    the assembly step entirely — useful for fast shape iteration when
    only the metadata content matters.
    """

    if not release_dir.exists():
        raise FileNotFoundError(f"release directory not found: {release_dir}")

    metadata = build_metadata(
        release_dir,
        tiers=tiers,
        task=task,
        owner=owner,
        dataset_slug=dataset_slug,
        title=title,
        subtitle=subtitle,
        description=description,
        keywords=keywords,
        license_name=license_name,
        update_frequency=update_frequency,
        user_sources=user_sources,
        cover_image=cover_image,
    )

    errors: list[ValidationError] = []
    errors.extend(validate_metadata(metadata))
    errors.extend(validate_cover_image(cover_image))
    errors.extend(_validate_readme_substitution(release_dir))

    metadata_path = kaggle_dir / "dataset-metadata.json"
    metadata_path.parent.mkdir(parents=True, exist_ok=True)
    metadata_path.write_text(render_metadata_json(metadata), encoding="utf-8")

    if not dry_run:
        assemble_upload_dir(release_dir, kaggle_dir, tiers=tiers, cover_image=cover_image)

    return PackagerOutcome(
        metadata=metadata,
        metadata_path=metadata_path,
        errors=tuple(errors),
        assembled=not dry_run,
    )


def _validate_readme_substitution(release_dir: Path) -> list[ValidationError]:
    """Guard against silent drift between the README's tree diagram
    and ``KAGGLE_TREE_BLOCK``.

    ``_kaggle_readme_text`` substitutes the source-repo tree diagram
    for the upload-tree diagram via plain string replace.  If the
    README's tree changes by even one whitespace character, the
    substitution silently no-ops and the published Kaggle dataset
    card shows the source-repo tree (with ``intermediate_instructor/``,
    ``notebooks/``, ``validation/``).  We catch that case here.
    """

    readme = release_dir / "README.md"
    if not readme.exists():
        return []  # No README is itself a release-day issue, but not this validator's concern.
    if KAGGLE_TREE_BLOCK not in readme.read_text(encoding="utf-8"):
        return [
            ValidationError(
                field="release/README.md",
                message=(
                    "KAGGLE_TREE_BLOCK not found verbatim in release/README.md; "
                    "the source-repo tree diagram in the README has drifted from "
                    "the constant in scripts/package_kaggle_release.py — the "
                    "Kaggle description rewrite will silently no-op until the "
                    "README and KAGGLE_TREE_BLOCK are reconciled."
                ),
            )
        ]
    return []


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate and validate Kaggle dataset-metadata.json for "
        "leadforge-lead-scoring-v1.",
    )
    parser.add_argument(
        "--release-dir",
        type=Path,
        default=DEFAULT_RELEASE_DIR,
        help="release bundle root containing one subdirectory per tier (default: %(default)s)",
    )
    parser.add_argument(
        "--kaggle-dir",
        type=Path,
        default=DEFAULT_KAGGLE_DIR,
        help="output directory for dataset-metadata.json (default: %(default)s)",
    )
    parser.add_argument(
        "--tier",
        action="append",
        dest="tiers",
        default=None,
        help="limit packaging to one tier (repeatable; default: intro/intermediate/advanced)",
    )
    parser.add_argument(
        "--owner",
        default=DEFAULT_USER_SLUG,
        help="Kaggle owner (user or organisation) prefix on the dataset id (default: %(default)s)",
    )
    parser.add_argument(
        "--dataset-slug",
        default=DEFAULT_DATASET_SLUG,
        help="dataset slug (must satisfy G1.2; default: %(default)s)",
    )
    parser.add_argument(
        "--cover-image",
        type=Path,
        default=DEFAULT_COVER_IMAGE,
        help="path to the dataset cover image (default: %(default)s)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="validate + write metadata only; skip assembling the upload directory",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = _parse_args(argv)
    kaggle_dir: Path = args.kaggle_dir
    tiers: tuple[str, ...] = tuple(args.tiers) if args.tiers else DEFAULT_TIERS

    try:
        outcome = run_packager(
            args.release_dir,
            kaggle_dir=kaggle_dir,
            tiers=tiers,
            owner=args.owner,
            dataset_slug=args.dataset_slug,
            cover_image=args.cover_image,
            dry_run=args.dry_run,
        )
    except FileNotFoundError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    if outcome.errors:
        print("validation failed:", file=sys.stderr)
        for err in outcome.errors:
            print(f"  - {err.field}: {err.message}", file=sys.stderr)
        return 1

    print(f"wrote {outcome.metadata_path}", file=sys.stderr)
    if outcome.assembled:
        print(f"assembled upload tree under {kaggle_dir}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
